name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'openmpi' ]

    steps:
    - uses: actions/checkout@v2
    
    - name: install-openmpi
      run: sudo apt install libopenmpi-dev openmpi-bin
      
    - name: build 
       # Build your program with the given configuration
      run: mkdir -p ${{github.workspace}}/build && cd ${{github.workspace}}/build && cmake .. && make

    - name: test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --rerun-failed --output-on-failure
